length=float(input("Enter Length of Rectangle:"))
breadth=float(input("Enter Breadth of Rectangle:"))
print("The Length of rectangle are as follows:", length)
print("The Breadth of Rectangle are as follows:",breadth)
print("Area of rectangle are as follows:",length*breadth)
