a=int(input("Enter 1st number"))
b=int(input("Enter 2nd number"))
c=int(input("Enter 3rd number"))
print("The three number are as follows:",a, b, c)
print("The sum of numbers are as follows:", a+b+c)
